---
name: YAML Lint

on:
  workflow_call:  # This allows other repositories to call this workflow

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      # - name: Show current dirr
      #   run: pwd

      # - name: check if bash installed
      #   run: which bash

      # - name: List all files in directory
      #   run: ls -R
        
      - name: Run yamllint
        run: yamllint .
