---
name: YAML Lint

on:
  workflow_call:  # This allows other repositories to call this workflow

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint
        
      - name: Run yamllint
        run: yamllint .
